name: Build and Deploy to Vercel

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install --prefix frontend


    - name: Build
      run: npm run build --prefix frontend
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel_token: ${{ secrets.VERCEL_TOKEN }}
        vercel_project_id: YOUR_VERCEL_PROJECT_ID
        build_dir: frontend/dist

