name: Build and Deploy to Vercel

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install --prefix frontend


    - name: Build
      run: npm run build --prefix frontend
      
    - name: Deploy to Vercel
      uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Set environment variables
      run: |
        echo "VAR1=value1" >> $GITHUB_ENV
        echo "VAR2=value2" >> $GITHUB_ENV

